# Generated by Django 5.0 on 2023-12-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='mark_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1'),
        ),
    ]
