# Generated by Django 5.0 on 2023-12-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mark_mark_2_alter_mark_mark_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='mark_2',
        ),
    ]
